@extends('layout')

@section('title', 'Quiz Cover Page')

@section('content')
<h3 class="allcaps center underline">Faculty of DRMTM Studies</h3>
<h3 class="allcaps center">Final Examination</h3>
<h1 class="center">{{$quiz->title}}</h1>
<p class="center">{{$quiz->description}}</p>
<p class="right">Date: {{today()->toFormattedDateString()}}</p>
<p class="left">Examiner: {{$quiz_master}}</p>
<p class="left">Associate Examiner: Phil Hwang, MSc, Joseph Szymborski, MSc</p>

<hr/>
<strong>Instructions:</strong>
<ol>
  <li>All students must write the exam in the room they are assigned, or at their computer.</li>
  <li>I.D. will be checked by the invigilator at the door, but not actually.</li>
  <li>Answers are entered by filling out the forms on the next page for {{$quiz->questions()->count()}} questions.</li>
  <li>It is intended there will be only <u>one answer per question</u>.</li>
  <li><u>Name and Student ID must be recorded in two places:</u> 1. On the <u>cover of the exam</u> and 2. Tattooed on <u>your chest</u>.</li>
  <li><u>Turn in the whole set of exam questions as well as the answer sheet</u> at the end of the exam.</li>
  <li>There will be multiple versions of the exam. <u>Don't enter it anywhere as there is no place to enter it, idiot</u></li>
  <li>Calculators are allowed in the exam room.</li>
  <li>A simple translation dictionary may be used during the exam by persons in their first year of study in English. Check with the invigilator.</li>
  <li>If you find any questions ambiguous, tough noogies you hozer.</li>
  <li>This is a closed book, open computer exam.</li>
</ol>

<p><strong>Don't panic! It is best to answer all the questions you know the answers to and come back to the others later lol jk that never works you're either fucked or you're not.</strong></p>

<p><strong><u>Warning:</u></strong> Examination Security Monitor Programme detects pairs of students with unusually similar answers patterns on multiple-choice exams. Data generated by this program can be used as admissible evidence, either to initiate or corroborate and investigation of a charge of cheating under Section 16 of the Code of Student Conduct and Disciplinary Procedures. I swear to God if you so much as think of the word Google or even like get two Ducks into DuckDuckGo I <em>will</em> find you and there will be disciplinary action. We have spies.</p>
<hr/>
<p class="center">Clicking the red "Turn Page" button starts the clock, giving you 90 minutes from <span id="time"></span></p>
<div class="center">
  <a href="/take/{{$quiz->id}}/qs" class="btn btn-danger">Turn Page</a>
</div>
<br/>
@verbatim
<script>
  // Make sure $wait_time has a valid format so that Date() can parse it.
var serverTime = new Date();

function updateTime() {
    /// Increment serverTime by 1 second and update the html for '#time'
    serverTime = new Date(serverTime.getTime() + 1000);

    $('#time').html(serverTime.toGMTString());
}

$(function() {
    updateTime();
    setInterval(updateTime, 1000);
});
  </script>
  @endverbatim
@endsection